# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Smart Product Advisor"
client_id = "923162968065"
application_url = "https://smart-product-advisor.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "smart-advisor-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_themes,read_themes"

[auth]
redirect_urls = [
  "https://smart-product-advisor.onrender.com/auth/callback",
  "https://smart-product-advisor.onrender.com/auth/shopify/callback",
  "https://smart-product-advisor.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"
