services:
  - type: web
    name: smart-product-advisor
    runtime: python
    region: ohio
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 30 --access-logfile '-' --error-logfile '-'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 1
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 30 --keep-alive 5 --log-level debug"
    healthCheckPath: /health
    autoDeploy: true
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 50
      targetCPUPercent: 50 