services:
  - type: web
    name: smart-product-advisor
    runtime: python
    region: ohio
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --worker-class gthread --threads 4 --timeout 180 --access-logfile '-' --error-logfile '-' --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 2
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 180 --keep-alive 5 --log-level debug"
    healthCheckPath: /health
    autoDeploy: true
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 70
      targetCPUPercent: 70

  - type: redis
    name: smart-advisor-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction 