name = "product-advisor"
type = "theme_app_extension"

[capabilities]
block_progress = true
customization = true
network_access = true

[[metafields]]
namespace = "smart_advisor"
key = "settings"

[[extensions]]
handle = "product-advisor"
type = "theme_app_extension"

[extensions.settings]
target = "body"
module = "./blocks/app.liquid"

[extensions.blocks]
name = "Smart Product Advisor"
type = "app_block"
target = "body"
module = "./blocks/product-advisor.liquid"

